### ISSUE TITLE
Image galleries from dickdrainers.com download.

### ISSUE THREAD

**Issue by waswosi** [arandom0/jdownloader-automated-gallery-download#1]
The site has some galleries where the download-link for the whole picture gallery zip file is missing. When you click on a pic a java slideshow opens. You can download every pic with right click.  Is there an automated way with this script?

**Comment by arandom0** [comment]
I can't tell. It requires a membership. A membership likely means that Jdownloader will not be able to download the images, BUT they could still realistically be downloaded using the browser itself (I will need to update the script to add that functionality).

Can you send me a link to an image? Open the full size image, copy its URL and send it here. (Or alternatively open a private window on your browser and see if the link opens there). If it does open, it means Jdownloader could download them. Otherwise they would need to be downloaded through the browser directly.


Other than that, since you have the membership you'd need to give me the CSS selectors for images. The variables under:
"//---------------------------------------------------
 // Per site"
in the script.

Or maybe you can save the page to an HTML file (right click, save page as, webpage complete), zip the file and folder it produces, and attach it in your future comments, so I can take a look.
